name: CI

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        configuration: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
          cmake --build build --config ${{ matrix.configuration }}
